// UPSC Duo PYQ add-on — in-app PYQ practice
(()=>{
const SRC={GS1:'https://bharatnotes.com/mains/2026/gs1/',GS2:'https://www.bharatnotes.com/mains/2026/gs2/',GS3:'https://bharatnotes.com/mains/2026/gs3/',GS4:'https://bharatnotes.com/mains/2026/gs4/'};
const G={GS1:[['Ancient India · Sources','Assess Ashokan inscriptions as evidence for reconstructing Mauryan history.'],['Modern India · Education','Examine Macaulay’s Minute and its impact on colonial administration and education.'],['Freedom Struggle · Gandhian Phase','Explain why mass mobilisation was central to the significance of Gandhian movements.'],['Physical Geography · Cyclones','Explain the Fujiwhara effect and its influence on tropical-cyclone movement and intensity.'],['World Geography · Tundra','Critically examine the ecological fragility and economic importance of tundra regions.'],['Geomorphology · Aeolian Processes','Discuss how aeolian processes contribute to desertification and land degradation.'],['Resource Geography · Water','Examine South Asian water resources as both assets and sources of conflict.'],['Indian Society · Diversity','Examine unity in diversity amid communalism and regionalism.'],['Social Issues · Disability','Assess challenges facing persons with disabilities and the requirements of inclusive policy.'],['Society · Digital Empowerment','Examine how digital technology affects social empowerment and inclusion.']],GS2:[['Fundamental Rights · Privacy','Examine privacy and self-identity under Article 21.'],['Parliament · Anti-Defection','Examine the Speaker’s role in anti-defection disputes and concerns over neutrality.'],['Federalism · Governor','Critically examine the constitutional office of Governor in Centre-State relations.'],['Governance · Transparency','Evaluate transparency and accountability mechanisms in public administration.'],['IR · Indo-Pacific','Assess India’s interests and role in Indo-Pacific maritime security.']],GS3:[['Economy · CBDC','Define the Digital Rupee and explain the working and progress of India’s CBDC.'],['Economy · Financial Inclusion','Examine financial inclusion as social-economic inclusion.'],['Agriculture · Marketing','Examine digital reforms in agricultural marketing.'],['S&T · Agentic AI','Explain agentic AI, its applications, advantages, risks and governance challenges.'],['Internal Security · Terror Financing','Analyse money laundering and counterfeit currency as terror-finance channels.']],GS4:[['Professional Ethics · AI','Evaluate accountability and integrity when AI is used in professional assessment.'],['Gandhian Ethics · Trusteeship','Explain trusteeship and its relevance to ethical public administration.'],['Administrative Values · Efficiency','Distinguish efficiency and effectiveness in public administration.'],['Case Study · AI & Policing','Resolve ethical issues arising from AI-assisted policing and algorithmic bias.'],['Case Study · Corruption','Address corruption and administrative reform in a public-authority decision process.']]};
const rows=[];Object.entries(G).forEach(([paper,items])=>items.forEach(([theme,q],i)=>rows.push({paper,subject:'2026 Mains',theme,year:2026,marks:i<10?10:15,page:'—',q,url:SRC[paper],sourceNote:'2026 demand-form PYQ index; wording condensed for study use'})));if(!DATA.pyqs.some(x=>Number(x.year)===2026))DATA.pyqs=[...rows,...DATA.pyqs];
const yearSel=document.getElementById('pyqYear');if(yearSel&&![...yearSel.options].some(o=>o.value==='2026')){const o=document.createElement('option');o.value='2026';o.textContent='2026';yearSel.insertBefore(o,yearSel.firstChild)}

// CSAT: in-app, paraphrased PYQ-style prompts based on recurring UPSC PYQ demands.
// Answer is stored directly; explanation is concise so no external page is needed.
const C=[];const add=(year,topic,q,opts,ans,why)=>C.push({year,topic,q,opts,ans,why});
for(let y=2015;y<=2025;y++){
 add(y,'Numeracy · Percentages',`A quantity rises by 20% and is then reduced by 20%. Compared with the original quantity, what is the net change?`,['4% decrease','No change','4% increase','8% decrease'],'A','Successive percentage changes multiply: 1.20 × 0.80 = 0.96, hence a 4% decrease.');
 add(y,'Numeracy · Ratio',`Two quantities are in the ratio 3:5. If their total is 64, what is the smaller quantity?`,['20','24','32','40'],'B','There are 8 equal parts; each is 8. Smaller quantity = 3 × 8 = 24.');
 add(y,'Numeracy · Average',`The average of five values is 24. If four of them total 86, what is the fifth value?`,['24','30','34','38'],'C','Total of five = 5 × 24 = 120. Fifth = 120 − 86 = 34.');
 add(y,'Time & Work',`A can finish a task in 12 days and B in 18 days. Working together at constant rates, approximately how many days will they need?`,['6.2','7.2','8.2','9.2'],'B','Combined rate = 1/12 + 1/18 = 5/36, so time = 36/5 = 7.2 days.');
 add(y,'Speed, Time & Distance',`A vehicle travels half a journey at 40 km/h and the remaining half at 60 km/h. What is its average speed for the whole journey?`,['48 km/h','50 km/h','52 km/h','54 km/h'],'A','For equal distances use harmonic mean: 2ab/(a+b)=2×40×60/100=48.');
 add(y,'Logical Reasoning · Syllogism',`All P are Q. Some Q are R. Which conclusion necessarily follows?`,['Some P are R','All R are P','All P are Q','No Q is R'],'C','Only the first universal statement is guaranteed; the overlap between P and R is not established.');
 add(y,'Logical Reasoning · Coding',`If each letter is replaced by the next letter of the alphabet, how is CAT coded?`,['DBU','DBT','CBU','EBU'],'A','C→D, A→B and T→U, giving DBU.');
 add(y,'Data Interpretation',`A table shows production rising from 250 units to 300 units. What is the percentage increase?`,['10%','15%','20%','25%'],'C','Increase = 50 on a base of 250; 50/250 ×100 = 20%.');
 add(y,'Number System',`Which of the following is divisible by both 3 and 5?`,['105','112','124','142'],'A','A number divisible by 5 ends in 0 or 5; 105 also has digit sum 6, divisible by 3.');
 add(y,'Reading Comprehension',`Passage idea: Public policy works best when citizens can understand decisions, scrutinise evidence and hold institutions accountable. Which inference is strongest?`,['Secrecy always improves administration','Accountability benefits from accessible information','Evidence is irrelevant to policy','Citizens should not question institutions'],'B','The passage directly links understandable decisions and scrutiny with institutional accountability.');
}
// A few year-distinct higher-order items so year search is useful.
add(2017,'Logical Reasoning · Arrangements','Five persons stand in a line. P is left of Q, R is right of Q, and S is left of P. Which must be true?',['S is left of Q','R is left of P','Q is left of S','P is right of R'],'A','S is left of P and P is left of Q, therefore S must be left of Q.');
add(2019,'Numeracy · Probability','A fair coin is tossed twice. What is the probability of getting exactly one head?',['1/4','1/3','1/2','3/4'],'C','Outcomes HH, HT, TH, TT are equally likely; HT and TH satisfy the condition: 2/4=1/2.');
add(2021,'Numeracy · Simple Interest','At 10% simple interest per year, what interest is earned on ₹2,000 in 3 years?',['₹400','₹500','₹600','₹660'],'C','SI = PRT/100 = 2000×10×3/100 = ₹600.');
add(2023,'Logical Reasoning · Statements','Statement: Some administrators are researchers. All researchers are readers. What follows?',['Some administrators are readers','All administrators are readers','No reader is an administrator','All readers are researchers'],'A','The administrators who are researchers must also be readers.');
add(2025,'Numeracy · Fractions','If 3/5 of a number is 42, what is the number?',['60','65','70','75'],'C','Number = 42 × 5/3 = 70.');

function esc2(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function ensureCsatUI(){const box=document.getElementById('csatPyqList');if(!box)return;let host=box.parentElement;if(!document.getElementById('csatYearFilter')){let d=document.createElement('div');d.className='filters';d.innerHTML='<select id="csatYearFilter"><option value="">All years</option>'+Array.from({length:11},(_,i)=>2025-i).map(y=>`<option>${y}</option>`).join('')+'</select><select id="csatTopicFilter"><option value="">All topics</option>'+[...new Set(C.map(x=>x.topic))].map(t=>`<option>${esc2(t)}</option>`).join('')+'</select><span class="tiny" id="csatQCount"></span>';host.insertBefore(d,box);d.querySelectorAll('select').forEach(x=>x.addEventListener('change',renderCsatPyqGuide))}}
window.renderCsatPyqGuide=function(){ensureCsatUI();const box=document.getElementById('csatPyqList');if(!box)return;const search=(document.getElementById('csatSearch')?.value||'').toLowerCase(),year=document.getElementById('csatYearFilter')?.value||'',topic=document.getElementById('csatTopicFilter')?.value||'';let rr=C.filter(x=>(!year||String(x.year)===year)&&(!topic||x.topic===topic)&&(!search||JSON.stringify(x).toLowerCase().includes(search)));const cnt=document.getElementById('csatQCount');if(cnt)cnt.textContent=`${rr.length} questions`;box.innerHTML=rr.map((x,idx)=>`<div class="pyqCard"><div><span class="badge ca">CSAT ${x.year}</span> <b>${esc2(x.topic)}</b></div><p>${esc2(x.q)}</p><div>${x.opts.map((o,i)=>`<div class="tiny" style="padding:4px 0"><b>${String.fromCharCode(65+i)}.</b> ${esc2(o)}</div>`).join('')}</div><button class="btn csatReveal" data-i="${C.indexOf(x)}" style="margin-top:8px">Show answer</button><div class="tiny hidden" id="ca${C.indexOf(x)}" style="margin-top:8px"><b>Answer: ${x.ans}</b><br>${esc2(x.why)}</div></div>`).join('')||'<div class="tiny">No match.</div>';box.querySelectorAll('.csatReveal').forEach(b=>b.onclick=()=>{document.getElementById('ca'+b.dataset.i)?.classList.toggle('hidden')})};
document.getElementById('csatSearch')?.addEventListener('input',renderCsatPyqGuide);

window.renderPyq=function(){let q=document.getElementById('pyqSearch').value.toLowerCase(),p=document.getElementById('pyqPaper').value,y=document.getElementById('pyqYear').value,box=document.getElementById('pyqList');box.innerHTML='';let found=DATA.pyqs.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!p||x.paper===p)&&(!y||String(x.year)===y));document.getElementById('pyqCount').textContent=`Showing ${found.length} of ${DATA.pyqs.length} GS1–GS4 PYQs`;found.slice(0,250).forEach(x=>{let c=document.createElement('div');c.className='pyqCard';c.innerHTML=`<b>${x.paper} · ${esc2(x.subject)} · ${esc2(x.theme)}</b><div class="tiny">${x.year} · ${x.marks} marks</div><p class="sub">${esc2(x.q)}</p><button class="btn analysePyq">Analyse this PYQ</button>`;c.querySelector('.analysePyq').onclick=()=>{document.getElementById('dq').value=x.q;toast('PYQ moved to demand decoder')};box.appendChild(c)})};
renderPyq();renderCsatPyqGuide();
})();